name: Run isort
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1.0.0
        with:
            requirements-files: "requirements.txt requirements-test.txt"